name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Hello world action'
        run: echo "Hello, world!"

      - name: fecha
        run: date
      
      - name: muestrame el contenido del directorio
        run: ls -la

     